### PR TITLE
Add support for HACs

### PR DESCRIPTION
**Pull request by rcastberg**
Add support for loading this integration in HACs, paste the github address to hacs and it can manage updates to your code.

### CODE REVIEW

**Comment by ndoty** [comment]
I upvote this. Please merge! First spot i looked was HACS. Havnt had to manually install a component in a long time... Until this one....

**Comment by FaserF** [comment]
Until this one is being merged, you can always add this repository as a custom repo, which is working fine

**Comment by ndoty** [comment]
> Until this one is being merged, you can always add this repository as a custom repo, which is working fine

I know, that is why i stated "Haven't had to manually install a component in a long time... Until this one...."

Most that are savy can install manually but HACs support is a bonus and the work is already done in this commit (Thanks @rcastberg ) This would be a great addition to the awesome component.

**Comment by pnbruckner** [comment]
Sorry, but I gave up on supporting HACS (which I had been doing with all of my custom integrations) a long time ago. It's a never ending moving target. Thanks anyway.

**Pull request closed without merging**
